name = "FooPack"
author = "oupson"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30ff4cb30e82ba941554c52edd758ddb6144aab9746609afb476c7407ae04024"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
