name = "FooPack"
author = "oupson"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5978726c30b9b84c8328fef43b0ae6523a4aaebe76f9b12bb2ad67023f19bda"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
